### ISSUE TITLE
error in running the package "spemd" 

### ISSUE THREAD

**Issue by hongfzh** [pierreroudier/spemd#1]
my code as follows:
texture <- raster("D:/14 spemd/elevation1.tif")
 g <- as(texture, 'SpatialGridDataFrame')
g$elevation1[is.na(g$elevation1)] <- 0
res.ncp <- spEMD(g, zcol = "depth", thresh.extrema = 0.1, verbose = FALSE)
The error is “Error in if (amplitude < 0) candidat <- candidat - 1 : argument is of length zero”. 

What's the matter? Thanks!

**Comment by pierreroudier** [comment]
@hongfzh any chance you could share the file "elevation1.tif" used in your example?

**Comment by hongfzh** [comment]
The attachment is the data. Thanks!




At 2018-02-08 13:11:58, "Pierre Roudier" <notifications@github.com> wrote:


@hongfzh any chance you could share the file "elevation1.tif" used in your example?

**Comment by hongfzh** [comment]
@pierreroudier, the attachment is the data. Thanks!

**Comment by hongfzh** [comment]
@pierreroudier,

the attachment is the data. Thanks!


[elevation1.zip](https://github.com/pierreroudier/spemd/files/1705811/elevation1.zip)

**Comment by pierreroudier** [comment]
@hongfzh You need to specify the correct name of the column you want to process using the `zcol` option. 

```
> names(g)
[1] "elevation1"
```

In the example you sent, the only column name is `elevation`, so yo need to use:

```
res.ncp <- spEMD(g, zcol = "elevation1", thresh.extrema = 0.1, verbose = FALSE)
```
